### PR TITLE
Bug fix #548

### LINKED ISSUE #548: Minor bug: the SDK throws a runtime error instead of returning details about a failure to connect to orderers
**Which SDK version am I using?**

v2.2.3

**Details of the issue**

Bug occurs due to a hard check on an object property failing in cases where `commitResponse` is `undefined`.

- This applies to the file `./fabric-network/src/transaction.ts` on lines 338 & 339 (`commitResponse.status` throws a hard error where `commitResponse` is `undefined`)

**Proposed fix**

I have already monkey-patched the pre-compiled `transaction.js` inside my Kuberneters network and confirmed that in this instance where the orderers are unable to connect it returns a useful error which is subsequently returned, for example, when running a Caliper test which uses the transpiled SDK to submit transactions.

I am happy to submit this fix as a PR as per @davidkel's suggestion, and can do this imminently assuming I have the ability to! I'm going to read the guidelines to see if I can do this without any input from a contributor.

### PR DESCRIPTION
**Pull request by sapthasurendran**
Closes #548

### CODE REVIEW

File: fabric-common/test/Commit.js [hunk 1]
```diff
@@ -106,6 +106,18 @@ describe('Commit', () => {
...
 
 	describe('#send', () => {
+		it('throws if targets committers is missing', async () => {
+			const stub = sinon.stub(channel, 'getTargetCommitters').callsFake(() => {
+				return undefined;
+			});
+			commit.build(idx);
+			const request = {
+				targets: [fakeCommitter]
+			};
```
Comment (bestbeforetoday) [inline fabric-common/test/Commit.js:116]: Looking at Channel.getTargetCommitters(), this will never return `undefined`. I think the error condition we should be testing for is where the request targets is an empty array, which means an empty array will be returned from Channel.getTargetCommitters(), and won't require that method to be stubbed.

Comment (bestbeforetoday) [inline fabric-common/test/Commit.js:116]: Looking at Channel.getTargetCommitters(), this will never return `undefined`. I think the error condition we should be testing for is where the request targets is an empty array, which means an empty array will be returned from Channel.getTargetCommitters(), and won't require that method to be stubbed.

File: fabric-network/test/transaction.js [hunk 2]
```diff
@@ -281,6 +281,12 @@ describe('Transaction', () => {
 			return expect(promise).to.be.eventually.rejectedWith(status).and.have.deep.property('responses', [validEnsorsementResponse]);
 		});
 
+		it.only('throws with peer responses if the orderer returns an undefined response', async () => {
```
Comment (bestbeforetoday) [inline fabric-network/test/transaction.js:284]: I'm not sure if a test is needed at this level. Certainly need to remove the `.only`. What is here now is faking out so much it's difficult to see any value.

Comment (bestbeforetoday) [inline fabric-network/test/transaction.js:284]: I'm not sure if a test is needed at this level. Certainly need to remove the `.only`. What is here now is faking out so much it's difficult to see any value.

**Review by bestbeforetoday — CHANGES_REQUESTED** [review]
See comments.

**Review by bestbeforetoday — APPROVED** [review]

**Comment by bestbeforetoday** [comment]
@Mergifyio backport release-2.2
